version: '3.8'

services:
  db:
    container_name: postgres_container
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - curso-quarkus

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:8.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8090:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - curso-quarkus

volumes:
  db-data:
  pgadmin-data:

networks:
  curso-quarkus:
    driver: bridge
